### ISSUE TITLE
Maintain project status automatically

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/automation#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the enhancement you have in mind and explain what the current shortcomings are?

Every approved or change-requested PR review status should also be manually updated in the `Ynteam planning` projects. This might not always happen because someone might forget.

### How would you imagine the implementation of the enhancement?

We could have worklflow which would do this automatically. 

We might also need to add additional status into Ynteam planning for `Change requested`, right @dee-ynput ?

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by philnewm** [comment]
Makes sense to me, I quickly checked what [GitHubs API](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved) offers here.

This docuementation example seems promising
```ymal
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
```
According to a quick ChatGPT request this should also work for change requests
```yaml
- name: Check review state
  run: |
    if [[ "${{ github.event.review.state }}" == "approved" ]]; then
      echo "The pull request was approved!"
      # Add your actions here for when the PR is approved
    elif [[ "${{ github.event.review.state }}" == "changes_requested" ]]; then
      echo "Changes were requested on the pull request!"
      # Add your actions here for when changes are requested
```

And also in this case we need a global way to control it and or let repositories inherit this workflow from the organization level.
